/**
 * Code-to-label mappings for article attributes (material, color, type).
 * Mirrors the constants defined in code-style/fastapi-app/app/constants/.
 */

type LabelEntry = { en: string; fr: string }

const MATERIALS: Record<string, LabelEntry> = {
  ma1:  { en: "Cotton",       fr: "Coton" },
  ma2:  { en: "Wool",         fr: "Laine" },
  ma3:  { en: "Leather",      fr: "Cuir" },
  ma4:  { en: "Denim",        fr: "Jeans" },
  ma5:  { en: "Cashmere",     fr: "Cachemire" },
  ma6:  { en: "Silk",         fr: "Soie" },
  ma7:  { en: "Lace",         fr: "Dentelle" },
  ma8:  { en: "Mesh",         fr: "Maille" },
  ma9:  { en: "Knit",         fr: "Tricot" },
  ma10: { en: "Linen",        fr: "Lin" },
  ma11: { en: "Acetate",      fr: "Acétate" },
  ma12: { en: "Acrylic",      fr: "Acrylique" },
  ma13: { en: "Brass",        fr: "Laiton" },
  ma14: { en: "Calfskin",     fr: "Cuir de veau" },
  ma15: { en: "Gold",         fr: "Or" },
  ma16: { en: "Silver",       fr: "Argent" },
  ma17: { en: "Bronze",       fr: "Bronze" },
  ma18: { en: "Steel",        fr: "Acier" },
  ma19: { en: "Metal",        fr: "Metal" },
  ma20: { en: "Platinum",     fr: "Platine" },
  ma21: { en: "Fishnet",      fr: "Résille" },
  ma22: { en: "Viscose",      fr: "Viscose" },
  ma23: { en: "Fake fur",     fr: "Fausse fourrure" },
  ma24: { en: "Fur",          fr: "Fourrure" },
  ma25: { en: "Latex",        fr: "Latex" },
  ma26: { en: "Muslin",       fr: "Mousseline" },
  ma27: { en: "Neoprene",     fr: "Neoprene" },
  ma28: { en: "Organza",      fr: "Organza" },
  ma29: { en: "Nylon",        fr: "Nylon" },
  ma30: { en: "Polyamide",    fr: "Polyamide" },
  ma31: { en: "Polyester",    fr: "Polyester" },
  ma32: { en: "PVC",          fr: "PVC" },
  ma33: { en: "Raffia",       fr: "Raffia" },
  ma34: { en: "Satin",        fr: "Satin" },
  ma35: { en: "Suede",        fr: "Suedine" },
  ma36: { en: "Straw",        fr: "Paille" },
  ma37: { en: "Tulle",        fr: "Tulle" },
  ma38: { en: "Tweed",        fr: "Tweed" },
  ma39: { en: "Velvet",       fr: "Velours" },
  ma40: { en: "Vinyl",        fr: "Vinyl" },
  ma41: { en: "Wax",          fr: "Wax" },
  ma42: { en: "Wicker",       fr: "Osier" },
  ma43: { en: "Other",        fr: "Autre" },
  ma48: { en: "Taffeta",      fr: "Taffeta" },
  ma49: { en: "Rubber",       fr: "Caoutchouc" },
  ma50: { en: "Canvas",       fr: "Toile" },
  ma51: { en: "Pearl",        fr: "Perle" },
  ma52: { en: "Jersey",       fr: "Jersey" },
  ma53: { en: "Feather",      fr: "Plumes" },
  ma54: { en: "Crepe",        fr: "Crepe" },
  ma55: { en: "Modal",        fr: "Modal" },
  ma56: { en: "Resin",        fr: "Résine" },
}

const COLORS: Record<string, LabelEntry> = {
  co1:  { en: "Black",       fr: "Noir" },
  co2:  { en: "White",       fr: "Blanc" },
  co3:  { en: "Blue",        fr: "Bleu" },
  co4:  { en: "Red",         fr: "Rouge" },
  co5:  { en: "Brown",       fr: "Marron" },
  co6:  { en: "Grey",        fr: "Gris" },
  co7:  { en: "Green",       fr: "Vert" },
  co8:  { en: "Yellow",      fr: "Jaune" },
  co9:  { en: "Beige",       fr: "Beige" },
  co10: { en: "Pink",        fr: "Rose" },
  co11: { en: "Purple",      fr: "Violet" },
  co12: { en: "Orange",      fr: "Orange" },
  co13: { en: "Gold",        fr: "Or" },
  co14: { en: "Silver",      fr: "Argent" },
  co15: { en: "Lilac",       fr: "Lilas" },
  co16: { en: "Camel",       fr: "Camel" },
  co17: { en: "Kaki",        fr: "Kaki" },
  co18: { en: "Multicolor",  fr: "Multicolore" },
  co19: { en: "Jeans",       fr: "Jeans" },
  co20: { en: "Navy",        fr: "Bleu marine" },
  co21: { en: "Bronze",      fr: "Bronze" },
  co22: { en: "Salmon",      fr: "Saumon" },
  co23: { en: "Transparent", fr: "Transparent" },
  co24: { en: "Ivory",       fr: "Ivoire" },
  co25: { en: "Taupe",       fr: "Taupe" },
  co26: { en: "Burgundy",    fr: "Bordeaux" },
  co27: { en: "Sand",        fr: "Sable" },
}

const ARTICLE_TYPES: Record<string, LabelEntry> = {
  ato1:  { en: "Dress",               fr: "Robe" },
  ato2:  { en: "Top & shirt",         fr: "Top et chemise" },
  ato3:  { en: "Trousers",            fr: "Pantalon" },
  ato4:  { en: "Jeans",               fr: "Jeans" },
  ato5:  { en: "Jacket & coat",       fr: "Veste & Manteau" },
  ato6:  { en: "Short",               fr: "Short" },
  ato7:  { en: "Skirt",               fr: "Jupe" },
  ato8:  { en: "Sweater & Cardigan",  fr: "Pull & Cardigan" },
  ato9:  { en: "Pyjamas",             fr: "Pyjama" },
  ato10: { en: "Jumpsuit",            fr: "Ensemble & Combinaison" },
  ato11: { en: "T-shirt",             fr: "T-shirt" },
  ato12: { en: "Knit",                fr: "Maille" },
  ato13: { en: "Jogging",             fr: "Sweat & Jogging" },
  ato14: { en: "Underwear",           fr: "Underwear" },
  ato15: { en: "Hoodie",              fr: "Hoodie" },
  ato16: { en: "Vest",                fr: "Gilet" },
  ata1:  { en: "Sunglasses",          fr: "Lunettes de soleil" },
  ata2:  { en: "Suspenders",          fr: "Bretelles" },
  ata3:  { en: "Socks",               fr: "Chaussettes" },
  ata4:  { en: "Hat",                 fr: "Chapeau" },
  ata5:  { en: "Scarf",               fr: "Écharpe & foulard" },
  ata6:  { en: "Hair accessories",    fr: "Accessoire de cheveux" },
  ata7:  { en: "Other",               fr: "Autre" },
  ata8:  { en: "Belt",                fr: "Ceinture" },
  ata9:  { en: "Cap",                 fr: "Bonnet & Casquette" },
  ata10: { en: "Bow & Tie",           fr: "Cravate & Noeud Papillon" },
  ata11: { en: "Gloves",              fr: "Gants" },
  ata12: { en: "Cufflinks",           fr: "Boutons de manchette" },
  ata13: { en: "Glasses",             fr: "Lunettes" },
  ats1:  { en: "Pumps",               fr: "Escarpins" },
  ats2:  { en: "Heeled sandals",      fr: "Sandales à talons" },
  ats3:  { en: "Slipper",             fr: "Mules & chaussons" },
  ats4:  { en: "Loafer & Flat shoes", fr: "Mocassins et Souliers plats" },
  ats5:  { en: "Boots",               fr: "Bottes & bottines" },
  ats6:  { en: "Sneakers",            fr: "Baskets" },
  ats7:  { en: "Sandals",             fr: "Sandales" },
  ats8:  { en: "Ballerina",           fr: "Ballerines" },
  ats9:  { en: "Espadrilles",         fr: "Espadrilles" },
  ats10: { en: "Heels",               fr: "Chaussures à talons" },
  atl1:  { en: "Handbag",             fr: "Sac à main" },
  atl2:  { en: "Shoulder strap",      fr: "Bandoulière" },
  atl3:  { en: "Backpack",            fr: "Sac à dos" },
  atl4:  { en: "Basket",              fr: "Cabas" },
  atl5:  { en: "Pouches & small leather goods", fr: "Pochettes et petite maroquinerie" },
  atl6:  { en: "Wallet",              fr: "Portefeuilles" },
  atl7:  { en: "Card holder & key ring", fr: "Porte-cartes & porte-clés" },
  atl8:  { en: "Travel bag",          fr: "Sac de voyage" },
  atl9:  { en: "Suitcase",            fr: "Valise" },
  atl10: { en: "Other",               fr: "Autre" },
  atl11: { en: "Tote Bag",            fr: "Tote Bag" },
  atw1:  { en: "Necklace",            fr: "Collier" },
  atw2:  { en: "Bracelet",            fr: "Bracelet" },
  atw3:  { en: "Earrings",            fr: "Boucle d'oreilles" },
  atw4:  { en: "Ring",                fr: "Bague" },
  atw5:  { en: "Watch & strap",       fr: "Montre & bracelet" },
  atw6:  { en: "Earcuff",             fr: "Earcuff" },
}

export function resolveMaterial(code: string | null, lang: "en" | "fr" = "en"): string | null {
  if (!code) return null
  return MATERIALS[code]?.[lang] ?? code
}

export function resolveColor(code: string | null, lang: "en" | "fr" = "en"): string | null {
  if (!code) return null
  return COLORS[code]?.[lang] ?? code
}

export function resolveArticleType(code: string | null, lang: "en" | "fr" = "en"): string | null {
  if (!code) return null
  return ARTICLE_TYPES[code]?.[lang] ?? code
}
